version: "3.8"

services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - vector-network
  remote-vector-index-builder:
    container_name: remote-vector-index-builder
    image: remote-vector-index-builder:e2e-latest
    command: >
      bash -c "pwd & fastapi run ../remote_vector_index_builder/app/main.py --port 1025 &
              sleep 5 &&
              python api/run_e2e.py"
    environment:
      - S3_ENDPOINT_URL=http://localstack-main:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - GPU_MEMORY_LIMIT=2
      - CPU_MEMORY_LIMIT=6
    ports:
      - "8080:1025"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - vector-network
    depends_on:
      - localstack

networks:
  vector-network:
    driver: bridge
